test: common test cases automation
matter-labs/dapp-portal pull request #75
Opened 2023-07-21 11:19 UTC by obmatter

2023-07-21 17:11 UTC, pcheremu requested changes

2023-07-21 17:11 UTC, pcheremu commented on .github/workflows/e2e.yml
>          ]
All these changes are necessary? Is this just an auto formatting?

2023-07-21 17:11 UTC, pcheremu commented on components/common/SmallInput.vue
> +  <component :is="as" :class="{ focused }" class="small-input-container">
You have to ask Danil for review this part of code.

2023-07-21 17:11 UTC, pcheremu commented on tests/e2e/features/artifacts/depositPage/tokens.feature
> +  @id1435:I @tokens
It is make sense to use @id1435:II id as it is the 2nd part of the test

2023-07-21 17:11 UTC, pcheremu commented on tests/e2e/features/artifacts/depositPage/tokens.feature
> +  @id1435:I @tokens
Please, add @testnet tag for testnet tests

2023-07-21 17:11 UTC, pcheremu commented on tests/e2e/features/artifacts/depositPage/tokens.feature
> +  @id1435:II @tokens
Please, add @mainnet tag for mainnet tests

2023-07-21 17:11 UTC, pcheremu commented on tests/e2e/features/artifacts/depositPage/tokens.feature
> +  @id1564 @id1436 @tokens
Also here we will need @mainnet tag (here and in general to be able to separate them next time)

2023-07-24 13:27 UTC, pcheremu requested changes

2023-07-24 13:27 UTC, pcheremu commented on tests/e2e/features/artifacts/depositPage/tokens.feature
> +    Then Element with "xpath" "//*[@class='modal-card']//*[contains(., '0xd35CCeEAD182dcee0F148EbaC9447DAas2c4D449c4')]" should be "visible"
Please, make this part more human readable: 
Element with "text" "No tokens was found" should be "visible"
Element with "text" "0xd35CCeEAD182dcee0F148EbaC9447DAas2c4D449c4" should be "visible"

2023-07-24 13:27 UTC, pcheremu commented on tests/e2e/features/artifacts/depositPage/tokens.feature
> +    Then Element with "xpath" "//*[@class='modal-card']//*[contains(., '0xd35CCeEAD182dcee0F148EbaC9447DAas2c4D449c4')]" should be "visible"
Also, please, add a new line #91

2023-07-24 13:27 UTC, pcheremu commented on tests/e2e/features/artifacts/depositPage/tokens.feature
> +    Then I fill the "data-testid=search_tokens" input field by "0xd35CCeEAD182dcee0F148EbaC9447DAas2c4D449c4"
Can you please check if it possible to update it in this way: 
I fill the "search_tokens" input field by "0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4"
or 
I fill the element of "data-testId" with "search_tokens" value by "0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4"

2023-07-24 13:27 UTC, pcheremu commented on tests/e2e/features/artifacts/depositPage/tokens.feature
> +  Scenario:  Check search functionality for Choose Tokens
Can you please split positive and negative scenarios.  Like @id1564:I and @id1564:II 
for positive you will be able to check ERC20 token as well as any other custom. and for negative you will be able to check any other tricky scenarios.

2023-07-25 12:43 UTC, obmatter commented
@pcheremu fixed all the comments - please take a look.
Thank you in advance!

2023-07-28 10:13 UTC, closed without merging